### PR TITLE
Add semicolons between styled-system mixins to unbreak formatting

### PR DESCRIPTION
**Pull request by mrm007**
## Description

Two changes in this PR:
- upgraded to Prettier 2.x
- fixed the issue with formatting `css` blocks (see below)

Many components have this situation going on (conditional CSS):

```js
const Blah = styled.marquee`
  ${color} ${fontWeight} ${fontSize} ${space} ${props =>
  props.underline &&
  css`
    &,
    &:hover {
      text-decoration: underline;
      color: inherit;
    }
  `} ${props =>
  props.hidden &&
  css`
    ${hideVisually()};
  `};
`;
```

or this one (mixins all on one line):

```js
const Blah = styled.blink`
  ${space} ${color} ${fontSize} ${lineHeight} ${border} ${borderColor} ${textAlign} display: block;
`;
```

```js
const Blah = styled.font`
  ${display} ${buttonStyle} ${space} ${color} ${boxShadow} ${width} &:hover {
    background-color: ${props => darken(0.1, getBackground(props))};
  }
`;
```

You will notice that Prettier doesn't work inside the `css` tagged template literal -- try it out by making some changes here: https://github.com/hooroo/roo-ui/blob/50c0918422320f155a9ce2dd37a1d75e87157771/src/components/Input/Input.js#L48

The solution is to add semicolons after each mixin/conditional block and Prettier will start working again.

## Looks like this

https://user-images.githubusercontent.com/3297808/128663403-c7ff1590-f711-4f6c-b00b-087906579ae4.mp4

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Angus](https://github.com/angusfretwell), [Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), or [Long](https://github.com/KieraDOG)).
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

### CODE REVIEW

**Review by philipwindeyer — APPROVED** [review]
🚀

**Review by memcc — APPROVED** [review]
Gotta love a prettier upgrade  🎉

**Comment by ehyland** [comment]
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: 944e1c803d7aaf135a95e3430ebc12ac44df1c4e

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/6111b30b8a5afa000762d178](https://app.netlify.com/sites/roo-ui/deploys/6111b30b8a5afa000762d178?utm_source=github&utm_campaign=bot_dl)

**Pull request merged**
