### PR TITLE
feat(media-counter-button): additional style customisation

### PR DESCRIPTION
**Pull request by chienleng**
## Description

💁‍ allow button label style customisation through the theme file and textStyles so Jetstar theme file can define them

## Related issues

💪 https://app.shortcut.com/qantasaccommodation/story/80547/property-page-desktop-image-gallery

## Looks like this

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [ ] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), [Marcel](https://github.com/Anthropic), [Sam](https://github.com/SamuSan) [Long](https://github.com/KieraDOG)) or a Roo UI working-group human.
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [ ] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

### CODE REVIEW

**Review by eneo5541 — CHANGES_REQUESTED** [review]
Hey mate, I apologize, I have not built this button well, that we keep coming back to the styling like this 😅 

I would like to avoid defining explicit props for padding, line-height and font-size. Basically, we want the component to be flexible to accept any styling without each styling needing to be defined as a prop, because that would quickly get bloated with props.

---

Basically, I was incorrect in setting the styling as part of an emotion styled component. This has greater specificity than prop styling, so style props do not work.  

A better way to do this (that I should have done before) is to define the styling as inline props like `px={3}` or `fontSize="sm"`
This lower specificity allows these props to be overridden by passing in style props. 

Implementation:
```
const MediaCounterButton = ({ totalImages, variant, onClick, textStyles, ...rest }) => {
  if (!totalImages) return null;

  return (
    <MediaCounterWrapper onClick={onClick} variant={variant} px={3} py={1} {...rest}>
      <Text fontSize="sm" {...textStyles}>
        View {totalImages > 1 ? `${totalImages} ` : ''}photo
        {totalImages > 1 ? 's' : ''}
      </Text>
    </MediaCounterWrapper>
  );
};
```

Usage:
```
    <MediaCounterButton
      variant="dark"
      totalImages={3}
      px={10}
      py={6}
      textStyles={{  fontSize: 'sm', lineHeight: '32px'  }}
    />
```

**Comment by chienleng** [comment]
No worries. Yeah, I think that should be workable. I will update the implementation 👍

**Comment by chienleng** [comment]
@eneo5541 changes updated. `borderRadius` is not supported for nakedButton so it's still in the styled component, but the textStyles prop will work.

**Review by eneo5541 — APPROVED** [review]

**Pull request merged**
