### PR TITLE
Add `focused` prop to `Input`

### PR DESCRIPTION
**Pull request by mrm007**
## Description

We are integrating Adyen in `{qantas,jetstar}-hotels-ui` and we need to be able to force focus on `Input` elements. This is necessary because of [the way Adyen works][works]: For each of card number, security code, CVV you provide an empty `div` and it renders an `iframe` with its own focus management. It's [pretty wild](https://github.com/hooroo/qantas-hotels-ui/blob/68aac84ae0fe59a2feb35d02d15fddf313287abb/cypress/e2e/smoke/checkout/common.js#L30-L44).

[works]: https://docs.adyen.com/payment-methods/cards/custom-card-integration

> **For web:** Build your own UI for the card payment form, and then use our Custom Card Web Component to collect, validate, and encrypt your shopper's card details. The Component renders card input fields in iframes served by Adyen.

> |Event|Description |
> |--|--|
> |`onFocus`| Called when a field gains focus.|

## Looks like this

image

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Angus](https://github.com/angusfretwell), [Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), or [Long](https://github.com/KieraDOG)).
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

### CODE REVIEW

**Review by philipwindeyer — APPROVED** [review]
🚀

**Review by memcc — APPROVED** [review]
Looks great!

Let me know if there are issues with this publishing a new version on merge.  It might only push to NPM for `feat:` and `fix:` commit prefixes.  @philipwindeyer any thoughts?

**Comment by mrm007** [comment]
Thanks for the heads up @memcc. I'll make sure to prefix the squash commit with `feat:`.

**Comment by philipwindeyer** [comment]
> Looks great!
> 
> Let me know if there are issues with this publishing a new version on merge. It might only push to NPM for `feat:` and `fix:` commit prefixes. @philipwindeyer any thoughts?

That's correct - a `fix:`, `feat:` or `BREAKING CHANGE` prefix (correlated with semantic versions `patch`, `minor` and `major`) will result in a new build pushed to NPM.

No prefix, or other semantic-aligned prefixes can be used to but don't result in a published package on npm

**Comment by ehyland** [comment]
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: f427eb1cbf08d45bb007dd0055ef105597112013

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/6111d65be1748e00099d554c](https://app.netlify.com/sites/roo-ui/deploys/6111d65be1748e00099d554c?utm_source=github&utm_campaign=bot_dl)

**Pull request merged**
