### PR TITLE
feat(logos): add new qantas logo

### PR DESCRIPTION
**Pull request by KamalMicheal**
:pear: @scara82

### CODE REVIEW

**Comment by angusfretwell** [comment]
Hey @KamalMicheal I think we should add this as a new logo, rather than replacing the Qantas logo, as it's not the Qantas logo, but the Qantas Hotels logo.

**Comment by angusfretwell** [comment]
Also, could you please run it through [svgo](https://github.com/svg/svgo) or [svgomg](https://jakearchibald.github.io/svgomg/) to remove the superfluous data from the SVG (e.g. Sketch metadata).

**Comment by KamalMicheal** [comment]
We totally agree @angusfretwell 
Done!

**Comment by angusfretwell** [comment]
@talbet All for adding the view box, but we've found that removing the height and width causes issues in IE11. FWIW this seems to be responsive already (i.e. I can set it to 100% width and it scales fine).

**Comment by talbet** [comment]
@angusfretwell OK, good call, would you suggest adding the viewbox attribute and not removing the width and height attributes?

**Comment by angusfretwell** [comment]
@talbet Yep I think that's ideal.

**Comment by KamalMicheal** [comment]
@talbet @angusfretwell Done!

**Pull request merged**
