### PR TITLE
chore: upgrade Storybook

### LINKED ISSUE #388: Storybook upgrade
Are we able to upgrade to the latest storybook? Previously we had issues with emotion

### PR DESCRIPTION
**Pull request by mrm007**
## Description

Upgraded Storybook to 6.3.6 (latest). Tested locally and everything looks good.

## Related issues

Closes #388

## Looks like this

image

image

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Angus](https://github.com/angusfretwell), [Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), or [Long](https://github.com/KieraDOG)).
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

### CODE REVIEW

**Comment by ehyland** [comment]
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: 259a093baf78fafd3e4a28ce5198c37241382993

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/6110689964b4e60008077905](https://app.netlify.com/sites/roo-ui/deploys/6110689964b4e60008077905?utm_source=github&utm_campaign=bot_dl)

**Review by eneo5541 — APPROVED** [review]
Confirmed working for me too! Great work!!

**Review by memcc — APPROVED** [review]
Looks great!

**Review by philipwindeyer — APPROVED** [review]
🚀

**Pull request merged**
