### PR TITLE
feat: add Inclusion component

### PR DESCRIPTION
**Pull request by klubiniecki-qantas**
## Description

Shortcut ticket: https://app.shortcut.com/qantasaccommodation/story/80784/procured-offers-inclusions

💁‍

## Related issues

💪

## Looks like this

Screen Shot 2021-11-11 at 1 39 51 pm

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), [Marcel](https://github.com/Anthropic), [Sam](https://github.com/SamuSan) [Long](https://github.com/KieraDOG)) or a Roo UI working-group human.
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

### CODE REVIEW

**Review by philipwindeyer — COMMENTED** [review]
Super neat! LGTM

One minor concern (and this is a nitpick more than anything really); I wonder if this is "too domain specific" for roo-ui, or at least the name of the component might be too specific. The only reason I say this is the overhaul a couple of years back where we opted to try and keep things as "generic" as possible and remove stuff some stuff that either only belonged to qantas-hotels-ui or needed a different home due to complex logic etc (like the calendar picker in qga-components for example).

Saying that, I can defs see this being used for more than just inclusions in procured offers - could work nicely for other UI compositions down the track too (can already think of a spot in self-service that would benefit from this despite not being "inclusions"). Makes me wonder if we could name it something other than `Inclusion`. Thoughts?

**Comment by klubiniecki-qantas** [comment]
> Super neat! LGTM
> 
> One minor concern (and this is a nitpick more than anything really); I wonder if this is "too domain specific" for roo-ui, or at least the name of the component might be too specific. The only reason I say this is the overhaul a couple of years back where we opted to try and keep things as "generic" as possible and remove stuff some stuff that either only belonged to qantas-hotels-ui or needed a different home due to complex logic etc (like the calendar picker in qga-components for example).
> 
> Saying that, I can defs see this being used for more than just inclusions in procured offers - could work nicely for other UI compositions down the track too (can already think of a spot in self-service that would benefit from this despite not being "inclusions"). Makes me wonder if we could name it something other than `Inclusion`. Thoughts?

Hey Phil!

I think that's a super valid point. A UI piece with icon, text and subtext is very generic and doesn't point in any way to `Inclusion` as such. How would we call it, when we look at functionality? `InfoField`? `InfoItem`? 😅

**Comment by philipwindeyer** [comment]
> 
> Hey Phil!
> 
> I think that's a super valid point. A UI piece with icon, text and subtext is very generic and doesn't point in any way to `Inclusion` as such. How would we call it, when we look at functionality? `InfoField`? `InfoItem`? 😅

`InfoField`, `InfoItem`, `InfoBox`, `InformationWithIcon`... not sure TBH. Naming in this context is not my forté 😅

**Review by philipwindeyer — APPROVED** [review]
Yeeeiiii 🚀 🌔

**Pull request merged**
