### PR TITLE
fix: pointsAndPayEnabled > pointsPlusPayEnabled, style tweaks

### PR DESCRIPTION
**Pull request by memcc**
## Description

Fixes:
- Consistent usage of `pointsPlusPayEnabled`
- Font color tweaks for primary button group variant
- Remove wrapping Flex from PayWithButtonGroup
- Fix types issue

💁‍

### CODE REVIEW

**Review by apisani — APPROVED** [review]
LGTM ✅

**Review by scara82 — APPROVED** [review]
It looks so nice and clean the component now, thanks! 🤩 🚀

**Review by philipwindeyer — APPROVED** [review]
🚀

**Pull request merged**
